// South-Korean stem-volume — SCAFFOLD ONLY, NO fabricated coefficients.
//
// The official national standard is the NIFoS / KFS 입목재적표 (2021), which is
// generated by NUMERICALLY integrating Kozak (1988) variable-exponent taper
// curves. As the primary source states, that stem curve cannot be integrated
// analytically, so there is no public closed-form V = f(D, H) for the official
// values. Independently-fitted closed-form models exist in the literature
// (e.g. combined-variable V = a + b·D²·H, Kang et al. 2017) but their
// coefficients were not retrievable from a reachable source this session
// (paywalled hosts). See docs/volume-standards-research.md §A.
//
// Per the project's honesty rule we therefore ship NO numbers and compute NO
// volume. Korea is still fully selectable: DBH, height, basal area and TPA are
// all unit-agnostic and work today. Stand-level volume renders "—" (callers
// branch on `VolumeStandard.isPending`) until official coefficients are wired
// into a real equation form here.

import Foundation

public struct KoreaNIFoS: VolumeEquation {

    /// Always true until verified official coefficients land. Present so a
    /// future implementer flips one flag rather than hunting call sites.
    public static let coefficientsPending = true

    public init(coefficients: [String: Float] = [:]) {}

    /// No coefficients ⇒ no volume. Returns 0 (never a fabricated estimate);
    /// the display layer shows "—" for pending-standard countries so this 0 is
    /// never mistaken for a real measurement.
    public func totalVolumeM3(dbhCm: Float, heightM: Float) -> Float { 0 }

    public func merchantableVolumeM3(dbhCm: Float, heightM: Float,
                                     topDibCm: Float, stumpHeightCm: Float) -> Float { 0 }
}
