// REQ-DBH-007 — opt-in raw scan persistence. Serialises the cleaned
// back-projected point set to ASCII PLY inside the app sandbox so the
// cruiser can later audit a measurement or reprocess it offline.
//
// The estimator hands us world-frame (x, z) pairs (breast-height slice).
// We pad Y = 0 so standard tools (MeshLab, CloudCompare, Preview) can
// load the file unchanged.

import Foundation

public enum PLYExporter {

    public enum Failure: Error {
        case directoryUnavailable
        case writeFailed(Error)
    }

    /// Build a writer closure suitable for `DBHScanInput.rawPointsWriter`.
    /// The closure writes `treeId.ply` under `directory/raw-scans/` and
    /// returns the absolute path on success or nil on failure.
    ///
    /// Pass `directory` = the project-scoped sandbox root (typically
    /// `URL.documentsDirectory.appending(path: project.id)`).
    public static func writer(
        directory: URL,
        treeId: UUID
    ) -> @Sendable ([SIMD2<Double>]) -> String? {
        { points in
            do {
                let url = try write(points: points,
                                    treeId: treeId,
                                    directory: directory)
                return url.path
            } catch {
                return nil
            }
        }
    }

    /// Write `points` as an ASCII PLY file. Creates `raw-scans/` if it
    /// doesn't exist. Returns the resulting file URL.
    public static func write(
        points: [SIMD2<Double>],
        treeId: UUID,
        directory: URL
    ) throws -> URL {
        let fm = FileManager.default
        let rawDir = directory.appendingPathComponent("raw-scans",
                                                     isDirectory: true)
        do {
            try fm.createDirectory(at: rawDir,
                                   withIntermediateDirectories: true)
        } catch {
            throw Failure.directoryUnavailable
        }
        let file = rawDir.appendingPathComponent(
            "\(treeId.uuidString).ply", isDirectory: false)
        let body = encodeASCII(points: points)
        do {
            try body.write(to: file, atomically: true, encoding: .utf8)
        } catch {
            throw Failure.writeFailed(error)
        }
        return file
    }

    /// Format a point set as ASCII PLY. Exposed for unit tests (no IO).
    public static func encodeASCII(points: [SIMD2<Double>]) -> String {
        var out = """
            ply
            format ascii 1.0
            comment Generated by TimberCruisingApp DBH scan (breast-height slice)
            element vertex \(points.count)
            property float x
            property float y
            property float z
            end_header

            """
        out.reserveCapacity(out.count + points.count * 24)
        for p in points {
            out.append("\(formatFloat(p.x)) 0 \(formatFloat(p.y))\n")
        }
        return out
    }

    private static func formatFloat(_ v: Double) -> String {
        // 6 significant digits — enough for millimetre precision without
        // bloating the file. Strip trailing zeros so round values stay
        // compact.
        String(format: "%.6g", v)
    }
}
